### PR TITLE
make it possible to set the default BU

### PR DESCRIPTION
**Pull request by lsmith77**

### CODE REVIEW

**Review by matweew — APPROVED** [review]

**Comment by tvaleriy** [comment]
As we can't merge it directly in split repository, I will create a ticket to make these changes in the right way and release this as a patch/minor.

**Comment by dereuromark** [comment]
Closing this then, as it has been moved into backlog.

**Comment by lsmith77** [comment]
how soon can we see this in a release? I was hoping such small things could happen faster ..

**Comment by tvaleriy** [comment]
https://github.com/spryker/business-on-behalf-data-import/releases/tag/1.1.0

**Pull request closed without merging**
